export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const INCREASE2 = 'INCREASE2';
export const DECREASE2 = 'DECREASE2';

export const FETCHING_USERS = 'FETCHING_USERS';
export const FETCHING_USERS_SUCCEDED = 'FETCHING_USERS_SUCCEDED';
export const FETCHING_USERS_ERROR = 'FETCHING_USERS_ERROR';

export const FETCHING_USER = 'FETCHING_USER';
export const FETCHING_USER_SUCCEDED = 'FETCHING_USER_SUCCEDED';
export const FETCHING_USER_ERROR = 'FETCHING_USER_ERROR';

export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';

export const SHOW_LOADRER = 'SHOW_LOADRER';
export const HIDE_LOADRER = 'HIDE_LOADRER';
